# Generated by Django 5.2.1 on 2025-05-16 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('emergency_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('vaccination_status', models.CharField(max_length=50)),
                ('vaccination_date', models.DateField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abseek.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('bite_site', models.CharField(max_length=100)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abseek.personalinfo')),
            ],
        ),
    ]
