# Generated by Django 5.2.1 on 2025-05-19 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abseek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='personal_info',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='IncidentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('bite_site', models.CharField(max_length=100)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='abseek.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('vaccination_status', models.CharField(max_length=50)),
                ('vaccination_date', models.DateField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='abseek.personalinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
