# Generated by Django 5.2.1 on 2025-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abseek', '0003_remove_incidentdata_personal_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_number',
            field=models.IntegerField(max_length=11),
        ),
    ]
