# Generated by Django 5.2.1 on 2025-05-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abseek', '0004_alter_personalinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
