# Generated by Django 5.2 on 2025-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abseek', '0006_alter_incidentdata_species_alter_personalinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentdata',
            name='case_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
