# Generated by Django 5.2 on 2025-05-22 03:37

import abseek.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abseek', '0007_alter_incidentdata_case_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentdata',
            name='case_id',
            field=models.CharField(default=abseek.models.generate_unique_case_id, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_id',
            field=models.CharField(default=abseek.models.generate_unique_patient_id, max_length=100, unique=True),
        ),
    ]
